server:
  port: 8080
fdfs:
  connect-timeout: 600
  so-timeout: 1500
  pool:
    jmx-enabled: false
  thumb-image:
    width: 100
    height: 50
    #跟踪器地址TrackerList参数,支持多个，我这里只有一个，如果有多个在下方加- x.x.x.x:port
  trackerList: 192.168.43.209:22122
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
